### ISSUE TITLE
ImportError: cannot import name QgsCodeEditorHTML

### ISSUE THREAD

**Issue by lionelbargeot** [3liz/lizmap-plugin#55]
Hi 

I don't know if it's a lizmap plugin issue or a Qgis issue or a python issue. When I use the demo project (montpellier) and try to configure/change popup template, I-ve got the following message :
`ImportError: cannot import name QgsCodeEditorHTML`
I'm working on an ubuntu package : 1:2.14.1+20trusty on Linux Mint 17.2

Thanks for help
Lionel

**Comment by mdouchin** [comment]
@slarosa Do you know what can cause this bug ? Is QScintilla2 installed in all platforms ?

**Comment by slarosa** [comment]
no idea, @lionelbargeot Do you get any error by running ```from qgis.gui import QgsCodeEditorHTML``` within the python console?

**Comment by lionelbargeot** [comment]
I've got the same error in the python console. 
I use this package from my distrib :
python-qscintilla2                           2.8.1-2ubuntu1

**Comment by lionelbargeot** [comment]
I downloaded nightly build deb package for qgis and python-qgis and the problem is still here

**Comment by lionelbargeot** [comment]
It works fine on a Xenial ubuntu with python-qscintilla2 2.9.1

**Comment by pcav** [comment]
Confirmed here: https://github.com/3liz/lizmap-plugin/issues/106
Sorry for the duplication.

**Comment by pcav** [comment]
Not exactly a duplicate though: in my case it happens at startup of the application.

**Comment by pcav** [comment]
Please note: in the compiled standard package the error does not pop up

**Comment by mdouchin** [comment]
@pcav it is not a lizmap plugin issue, but more a package/configuration. Please ask the qgis-dev list, to gather more help. You should focus of the bug which happens when trying
 `from qgis.gui import QgsCodeEditorHTML` in QGIS Python console

**Comment by pcav** [comment]
Il 04/07/2018 08:36, mdouchin ha scritto:
> @pcav <https://github.com/pcav> it is not a lizmap plugin issue, but
> more a package/configuration. Please ask the qgis-dev list, to gather
> more help. You should focus of the bug which happens when trying
> |from qgis.gui import QgsCodeEditorHTML| in QGIS Python console

merci bien!

-- 
Paolo Cavallini - www.faunalia.eu
QGIS & PostGIS courses: http://www.faunalia.eu/training.html
https://www.google.com/trends/explore?date=all&geo=IT&q=qgis,arcgis

**Comment by Gustry** [comment]
As @mdouchin this is not a Lizmap issue.

`from qgis.gui import QgsCodeEditorHTML` works well for me.
